#if 0
/* ---------- headers */

#include "decomp.h"
#include <errno.h>
#include <boost\config\suffix.hpp>
#include <securitybaseapi.h>
#include <boost\bind\mem_fn_cc.hpp>
#include <oleidl.h>
#include <mcx.h>
#include <cstring>
#include <cwchar>
#include <wchar.h>
#include <crtdefs.h>
#include <swprintf.inl>
#include <debugapi.h>
#include <fileapi.h>
#include <cderr.h>
#include <dde.h>
#include <objidl.h>
#include <msxml.h>
#include <boost\type_traits\is_same.hpp>
#include <winsock2.h>
#include <winapifamily.h>
#include <windows.h>
#include <sdkddkver.h>
#include <threadpoollegacyapiset.h>
#include <rpcnterr.h>
#include <winsmcrd.h>
#include <dplay8.h>
#include <intrin.h>
#include <excpt.h>
#include <poppack.h>
#include <rpcnsi.h>
#include <rpcasync.h>
#include <dpaddr.h>
#include <setjmp.h>
#include <boost\mem_fn.hpp>
#include <new>
#include <boost\thread\thread.hpp>
#include <boost\assert.hpp>
#include <boost\get_pointer.hpp>
#include <boost\preprocessor\enum.hpp>
#include <boost\utility.hpp>
#include <xstddef>
#include <boost\type_traits\arithmetic_traits.hpp>
#include <boost\preprocessor\repetition\enum.hpp>
#include <boost\utility\addressof.hpp>
#include <boost\type_traits\is_arithmetic.hpp>
#include <boost\preprocessor\debug\error.hpp>
#include <boost\detail\workaround.hpp>
#include <boost\type_traits\is_integral.hpp>
#include <boost\type_traits\detail\ice_not.hpp>
#include <boost\preprocessor\detail\auto_rec.hpp>
#include <boost\type_traits\detail\bool_trait_def.hpp>
#include <boost\preprocessor\control\iif.hpp>
#include <boost\type_traits\detail\template_arity_spec.hpp>
#include <boost\preprocessor\punctuation\comma_if.hpp>
#include <mmiscapi2.h>
#include <ime_cmodes.h>
#include <boost\utility\base_from_member.hpp>
#include <boost\mpl\aux_\template_arity_fwd.hpp>
#include <boost\preprocessor\control\if.hpp>
#include <profileapi.h>
#include <boost\utility_fwd.hpp>
#include <boost\bind\mem_fn_template.hpp>
#include <boost\preprocessor\logical\bool.hpp>
#include <boost\mpl\aux_\preprocessor\params.hpp>
#include <boost\preprocessor\facilities\empty.hpp>
#include <synchapi.h>
#include <boost\mpl\aux_\config\preprocessor.hpp>
#include <boost\preprocessor\punctuation\comma.hpp>
#include <mmsystem.h>
#include <boost\mpl\aux_\lambda_support.hpp>
#include <boost\preprocessor\repetition\repeat.hpp>
#include <mmsyscom.h>
#include <process.h>
#include <boost\mpl\aux_\config\lambda.hpp>
#include <boost\preprocessor\tuple\eat.hpp>
#include <utilapiset.h>
#include <heapapi.h>
#include <processthreadsapi.h>
#include <ws2def.h>
#include <xlocinfo>
#include <boost\mpl\aux_\config\ttp.hpp>
#include <boost\preprocessor\tuple\rem.hpp>
#include <ole2.h>
#include <inaddr.h>
#include <xlocinfo.h>
#include <boost\mpl\aux_\config\overload_resolution.hpp>
#include <boost\preprocessor\enum_params.hpp>
#include <objbase.h>
#include <atlbase.inl>
#include <ctype.h>
#include <boost\mpl\bool.hpp>
#include <boost\preprocessor\repetition\enum_params.hpp>
#include <combaseapi.h>
#include <boost\mpl\bool_fwd.hpp>
#include <boost\preprocessor\repeat.hpp>
#include <boost\preprocessor\inc.hpp>
#include <pshpack8.h>
#include <winnetwk.h>
#include <qos.h>
#include <boost\preprocessor\iteration\detail\iter\forward1.hpp>
#include <wnnc.h>
#include <memory>
#include <boost\type_traits\composite_traits.hpp>
#include <boost\type_traits\detail\ice_eq.hpp>
#include <boost\preprocessor\iteration\detail\bounds\lower1.hpp>
#include <boost\thread\mutex.hpp>
#include <stdarg.h>
#include <cfloat>
#include <stdint.h>
#include <boost\type_traits\is_array.hpp>
#include <boost\preprocessor\slot\detail\shared.hpp>
#include <boost\thread\detail\lock.hpp>
#include <windef.h>
#include <float.h>
#include <boost\type_traits\config.hpp>
#include <boost\preprocessor\iteration\detail\bounds\upper1.hpp>
#include <boost\thread\exceptions.hpp>
#include <minwindef.h>
#include <bemapiset.h>
#include <rpcdcep.h>
#include <crtwrn.h>
#include <share.h>
#include <boost\function\detail\function_iterate.hpp>
#include <boost\thread\detail\config.hpp>
#include <specstrings.h>
#include <playsoundapi.h>
#include <boost\mpl\aux_\config\static_constant.hpp>
#include <boost\function\detail\maybe_include.hpp>
#include <specstrings_strict.h>
#include <boost\function\function_template.hpp>
#include <specstrings_undef.h>
#include <handleapi.h>
#include <boost\checked_delete.hpp>
#include <driverspecs.h>
#include <objidlbase.h>
#include <immintrin.h>
#include <sdv_driverspecs.h>
#include <ncrypt.h>
#include <wmmintrin.h>
#include <nmmintrin.h>
#include <threadpoolapiset.h>
#include <unknwnbase.h>
#include <xtgmath.h>
#include <smmintrin.h>
#include <oaidl.h>
#include <tmmintrin.h>
#include <boost\type_traits\is_class.hpp>
#include <commdlg.h>
#include <pmmintrin.h>
#include <boost\type_traits\is_union.hpp>
#include <vector>
#include <namespaceapi.h>
#include <emmintrin.h>
#include <boost\type_traits\remove_cv.hpp>
#include <ktmtypes.h>
#include <xmmintrin.h>
#include <boost\type_traits\broken_compiler_spec.hpp>
#include <mmintrin.h>
#include <boost\type_traits\detail\cv_traits_impl.hpp>
#include <dpapi.h>
#include <propidl.h>
#include <unknwn.h>
#include <boost\type_traits\is_enum.hpp>
#include <winbase.h>
#include <wincon.h>
#include <mmiscapi.h>
#include <wtime.inl>
#include <xatomic0.h>
#include <string>
#include <boost\type_traits\add_reference.hpp>
#include <apisetcconv.h>
#include <mmeapi.h>
#include <imm.h>
#include <iterator>
#include <boost\type_traits\is_reference.hpp>
#include <minwinbase.h>
#include <istream>
#include <atlcore.h>
#include <ostream>
#include <xdebug>
#include <winscard.h>
#include <tchar.h>
#include <ios>
#include <wtypes.h>
#include <mbstring.h>
#include <boost\next_prior.hpp>
#include <xlocnum>
#include <errhandlingapi.h>
#include <rpcndr.h>
#include <xutility>
#include <streambuf>
#include <boost\type_traits\detail\type_trait_def.hpp>
#include <processenv.h>
#include <rpcnsip.h>
#include <xiosbase>
#include <guiddef.h>
#include <stralign.h>
#include <xlocale>
#include <boost\ref.hpp>
#include <typeinfo>
#include <jobapi.h>
#include <boost\noncopyable.hpp>
#include <apiset.h>
#include <xfacet>
#include <boost\type_traits\is_pointer.hpp>
#include <winsvc.h>
#include <systemtopologyapi.h>
#include <pshpack1.h>
#include <atltransactionmanager.h>
#include <wow64apiset.h>
#include <ktmw32.h>
#include <atliface.h>
#include "\HICKORY-PCSHIP\Homeworld2Classic\src\Source\NetworkDP8\pch.h"
#include "\HICKORY-PCSHIP\Homeworld2Classic\src\Source\NetworkDP8\source\directplaydeleter.h"
#include <winnls.h>
#include <shellapi.h>
#include <shlwapi.h>
#include "\HICKORY-PCSHIP\Homeworld2Classic\src\Source\NetworkDP8\source\directplay.h"
#include <datetimeapi.h>
#include <shtypes.h>
#include <boost\cstdint.hpp>
#include <winnt.h>
#include <processtopologyapi.h>
#include <boost\config.hpp>
#include <kernelspecs.h>
#include <urlmon.h>
#include <boost\config\user.hpp>
#include <basetsd.h>
#include <pshpack2.h>
#include <boost\config\select_compiler_config.hpp>
#include <boost\throw_exception.hpp>
#include <libloaderapi.h>
#include <boost\config\compiler\visualc.hpp>
#include <sysinfoapi.h>
#include <boost\config\select_stdlib_config.hpp>
#include <atlchecked.h>
#include <utility>
#include <boost\function.hpp>
#include <boost\function\function_base.hpp>
#include <winreg.h>
#include <bcrypt.h>
#include <atlexcept.h>
#include <iosfwd>
#include <boost\preprocessor\iterate.hpp>
#include <stdexcept>
#include <atltrace.h>
#include <oleacc.h>
#include <cstdio>
#include <boost\preprocessor\iteration\iterate.hpp>
#include <xstring>
#include <atlconv.h>
#include <stdio.h>
#include <boost\preprocessor\arithmetic\dec.hpp>
#include <boost\type_traits\detail\ice_or.hpp>
#include <winsock.h>
#include <atlalloc.h>
#include <boost\preprocessor\config\config.hpp>
#include <nb30.h>
#include <wincrypt.h>
#include <boost\preprocessor\arithmetic\inc.hpp>
#include <boost\type_traits\has_trivial_copy.hpp>
#include <type_traits>
#include <boost\preprocessor\array\elem.hpp>
#include <boost\type_traits\is_volatile.hpp>
#include <boost\preprocessor\array\data.hpp>
#include <timeapi.h>
#include <boost\preprocessor\tuple\elem.hpp>
#include <boost\preprocessor\array\size.hpp>
#include <boost\preprocessor\cat.hpp>
#include <securityappcontainer.h>
#include <rpcsal.h>
#include <boost\preprocessor\slot\slot.hpp>
#include <climits>
#include <fibersapi.h>
#include <boost\preprocessor\slot\detail\def.hpp>
#include <cmath>
#include <boost\pending\ct_if.hpp>
#include <boost\function\detail\prologue.hpp>
#include <math.h>
#include <cassert>
#include <winver.h>
#include <crtdbg.h>
#include <assert.h>
#include <list>
#include <verrsrc.h>
#include <oleauto.h>
#include <algorithm>
#include <boost\type_traits\is_stateless.hpp>
#include <winioctl.h>
#include <servprov.h>
#include <xmemory>
#include <boost\type_traits\has_trivial_constructor.hpp>
#include <realtimeapiset.h>
#include <tvout.h>
#include <xmemory0>
#include <boost\type_traits\is_pod.hpp>
#include <mciapi.h>
#include <comcat.h>
#include <cstdlib>
#include <boost\type_traits\is_scalar.hpp>
#include <winuser.h>
#include <limits>
#include <cguid.h>
#include <ymath.h>
#include <boost\type_traits\has_trivial_destructor.hpp>
#include <atlsimpcoll.h>
#include <boost\type_traits\intrinsics.hpp>
#include <consoleapi.h>
#include <boost\config\stdlib\dinkumware.hpp>
#include <namedpipeapi.h>
#include <ioapiset.h>
#include <boost\config\select_platform_config.hpp>
#include <xrefwrap>
#include <boost\config\platform\win32.hpp>
#include <memoryapi.h>
#include <dlgs.h>
#include <winperf.h>
#include <statreg.h>
#include <wtypesbase.h>
#include <winspool.h>
#include <atlwinverapi.h>
#include <boost\type_traits\detail\type_trait_undef.hpp>
#include <prsht.h>
#include <boost\type_traits\is_convertible.hpp>
#include <boost\type_traits\detail\bool_trait_undef.hpp>
#include <boost\type_traits\detail\yes_no_type.hpp>
#include <boost\type_traits\is_empty.hpp>
#include <pshpack4.h>
#include <wingdi.h>
#include <boost\type_traits\is_float.hpp>
#include <rpc.h>
#include <ammintrin.h>
#include <boost\type_traits\is_member_pointer.hpp>
#include <mm3dnow.h>
#include <boost\type_traits\is_member_function_pointer.hpp>
#include <joystickapi.h>
#include <boost\type_traits\detail\is_mem_fun_pointer_impl.hpp>
#include <rpcdce.h>
#include <winerror.h>
#include <winefs.h>
#include <locale.h>
#include <ddeml.h>
#include <lzexpand.h>
#include <boost\type_traits\is_fundamental.hpp>
#include <atlbase.h>
#include <boost\type_traits\is_void.hpp>
#include <boost\type_traits\ice.hpp>
#include <atldef.h>
#include <atlcomcli.h>
#include <system_error>
#include <boost\type_traits\detail\ice_and.hpp>
#include <atlrc.h>
#include <olectl.h>
#include <cerrno>
#include <new.h>
#include <interlockedapi.h>
#include <timezoneapi.h>
#include <stringapiset.h>
#include <reason.h>
#include <ocidl.h>

/* ---------- constants */

/* ---------- definitions */

/* ---------- prototypes */

/* ---------- globals */

/* ---------- private variables */

_static
{
    extern std::allocator_arg_t allocator_arg; // 0x84CB9B
    extern std::piecewise_construct_t piecewise_construct; // 0x84CB9A
}

/* ---------- public code */

_extern _sub_6D8717(Net::DirectPlayDeleter *const, Net::DirectPlay::Context *, IDirectPlay8Peer *);
Net::DirectPlayDeleter::DirectPlayDeleter(Net::DirectPlay::Context *, IDirectPlay8Peer *) // 0x6D8717
{
    mangled_assert("??0DirectPlayDeleter@Net@@QAE@PAUContext@DirectPlay@1@PAUIDirectPlay8Peer@@@Z");
    todo("implement");
    _sub_6D8717(this, arg, arg);
}

_extern void _sub_6D872B(Net::DirectPlayDeleter *const);
void Net::DirectPlayDeleter::operator()() // 0x6D872B
{
    mangled_assert("??RDirectPlayDeleter@Net@@QAEXXZ");
    todo("implement");
    _sub_6D872B(this);
}

/* ---------- private code */
#endif
