#ifndef __GLEXTERNS_H__
#define __GLEXTERNS_H__
#pragma once

/* ---------- headers */

/* ---------- constants */

/* ---------- definitions */

struct HPBUFFERARB__
{
    __int32 unused; // 0x0
};
static_assert(sizeof(HPBUFFERARB__) == 4, "Invalid HPBUFFERARB__ size");

/* ---------- prototypes */

/* ---------- globals */

/* ---------- public code */

/* ---------- private code */

#endif // __GLEXTERNS_H__
