#if 0
#ifndef __PEERCALLBACKS_H__
#define __PEERCALLBACKS_H__
#pragma once

/* ---------- headers */

/* ---------- constants */

enum piCallbackType
{
    PI_CONNECT_CALLBACK = 0,
    PI_JOIN_ROOM_CALLBACK,
    PI_LIST_GROUP_ROOMS_CALLBACK,
    PI_LISTING_GAMES_CALLBACK,
    PI_NICK_ERROR_CALLBACK,
    PI_ENUM_PLAYERS_CALLBACK,
    PI_GET_PLAYER_PROFILE_ID_CALLBACK,
    PI_GET_PLAYER_IP_CALLBACK,
    PI_ROOM_MESSAGE_CALLBACK,
    PI_ROOM_UTM_CALLBACK,
    PI_ROOM_NAME_CHANGED_CALLBACK,
    PI_ROOM_MODE_CHANGED_CALLBACK,
    PI_PLAYER_MESSAGE_CALLBACK,
    PI_PLAYER_UTM_CALLBACK,
    PI_READY_CHANGED_CALLBACK,
    PI_GAME_STARTED_CALLBACK,
    PI_PLAYER_JOINED_CALLBACK,
    PI_PLAYER_LEFT_CALLBACK,
    PI_KICKED_CALLBACK,
    PI_NEW_PLAYER_LIST_CALLBACK,
    PI_PLAYER_CHANGED_NICK_CALLBACK,
    PI_PLAYER_INFO_CALLBACK,
    PI_DISCONNECTED_CALLBACK,
    PI_PING_CALLBACK,
    PI_CROSS_PING_CALLBACK,
    PI_CHANGE_NICK_CALLBACK,
    PI_GLOBAL_KEY_CHANGED_CALLBACK,
    PI_ROOM_KEY_CHANGED_CALLBACK,
    PI_GET_GLOBAL_KEYS_CALLBACK,
    PI_GET_ROOM_KEYS_CALLBACK,
    PI_PLAYER_FLAGS_CHANGED_CALLBACK,
    PI_AUTHENTICATE_CDKEY_CALLBACK,
    PI_NUM_CALLBACK_TYPES,
};

/* ---------- definitions */

/* ---------- prototypes */

/* ---------- globals */

/* ---------- public code */

/* ---------- private code */

#endif // __PEERCALLBACKS_H__
#endif
